-- 강원도에 위치한 생산공장 목록 출력하기
SELECT FACTORY_ID,
    FACTORY_NAME,
    ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID


-- 경기도에 위치한 식품창고 목록 출력하기
SELECT WAREHOUSE_ID,
    WAREHOUSE_NAME,
    ADDRESS,
    IFNULL(FREEZER_YN,'N')
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID


-- 나이 정보가 없는 회원 수 구하기
SELECT COUNT(USER_ID) AS 'USERS'
FROM USER_INFO
WHERE AGE IS NULL


-- 가장 비싼 상품 구하기
SELECT MAX(PRICE) AS 'MAX_PRICE'
FROM PRODUCT 


-- 조건에 맞는 회원수 구하기
SELECT COUNT(USER_ID) AS 'USERS'
FROM USER_INFO
WHERE DATE_FORMAT(JOINED,'%Y')=2021
AND AGE >=20 and AGE<=29 


-- 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR_NAME,
    DR_ID,
    MCDP_CD,
    DATE_FORMAT(HIRE_YMD,'%Y-%m-%d')
FROM DOCTOR
WHERE MCDP_CD = 'CS' or MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME ASC


-- 12세 이하인 여자 환자 목록 출력하기
SELECT PT_NAME,
    PT_NO,
    GEND_CD,
    AGE,
    IFNULL(TLNO, 'NONE') AS 'TLNO'
FROM PATIENT 
WHERE AGE<=12
AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME


-- 인기있는 아이스크림
SELECT FLAVOR
FROM FIRST_HALF 
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC


-- 조건에 맞는 도서 리스트 출력하기
SELECT BOOK_ID,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS 'PUBLISHED_DATE'
FROM BOOK
WHERE CATEGORY='인문' and
DATE_FORMAT(PUBLISHED_DATE, '%Y') = 2021
ORDER BY PUBLISHED_DATE


-- 평균 일일 대여 요금 구하기
SELECT ROUND(AVG(DAILY_FEE),0) AS 'AVERAGE_FEE'
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE='SUV'


-- 과일로 만든 아이스크림 고르기
SELECT f.FLAVOR
FROM FIRST_HALF AS f
INNER JOIN ICECREAM_INFO AS i
ON f.FLAVOR = i.FLAVOR
WHERE f.TOTAL_ORDER>3000
AND i.INGREDIENT_TYPE = 'fruit_based'


-- 특정 옵션이 포함된 자동차 리스트 구하기
SELECT *
FROM CAR_RENTAL_COMPANY_CAR 
WHERE OPTIONS like '%네비게이션%'
ORDER BY CAR_ID DESC


-- 자동차 대여 기록에서 장기/단기 대여 구분하기
SELECT HISTORY_ID,
    CAR_ID,
    DATE_FORMAT(START_DATE,'%Y-%m-%d') AS 'START_DATE',
    DATE_FORMAT(END_DATE,'%Y-%m-%d') AS 'END_DATE',
    IF(DATEDIFF(END_DATE,START_DATE)>=29, '장기 대여', '단기 대여') AS 'RENT_TYPE'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-09-01' AND '2022-09-30'
ORDER BY HISTORY_ID DESC


-- 조건에 부합하는 중고거래 댓글 조회하기
-- * WHERE절에서 r.CREATED_DATE가 아닌 b.CREATED_DATE로 해야 함!
SELECT b.TITLE,
    b.BOARD_ID,
    r.REPLY_ID,
    r.WRITER_ID,
    r.CONTENTS, 
    DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS 'CREATED_DATE'
FROM USED_GOODS_REPLY AS r
INNER JOIN USED_GOODS_BOARD AS b
ON r.BOARD_ID = b.BOARD_ID
WHERE b.CREATED_DATE BETWEEN '2022-10-01' and '2022-10-31'
ORDER BY CREATED_DATE, TITLE
