-- 중복 제거하기
SELECT COUNT(distinct(NAME))
FROM ANIMAL_INS

-- 아픈 동물 찾기 
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'

-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE
    ,COUNT(ANIMAL_ID) AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

-- 여러 기준으로 정렬하기
-- (이름 순으로 조회. 단, 이름이 같은 동물은 보호를 나중에 시작한 동물을 먼저 보여준다)
SELECT ANIMAL_ID
	,NAME
	,DATETIME
FROM ANIMAL_INS
ORDER BY 2, 3 DESC

-- 상위 n개 레코드
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

-- 이름이 없는 동물의 아이디
-- (※ NAME=NULL 과 IS NULL 차이)
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID

-- 루시와 엘라 찾기
SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME in ('Lucy','Ella','Pickle','Rogan','Sabrina','Mitty')
ORDER BY ANIMAL_ID

-- 동명 동물 수 찾기
-- (※ WHERE절은 집계함수 사용 불가)
SELECT NAME, COUNT(NAME) AS 'COUNT'
FROM ANIMAL_INS
GROUP BY NAME HAVING COUNT(NAME)>1
ORDER BY NAME

-- 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE ANIMAL_TYPE='Dog' and NAME LIKE '%el%'
ORDER BY NAME

-- NULL 처리하기
SELECT ANIMAL_TYPE,
    IFNULL(NAME, 'No name'),
    SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

-- 입양 시각 구하기(1)
SELECT HOUR(DATETIME) AS 'HOUR'
	, COUNT(ANIMAL_ID) AS 'COUNT'
FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME) HAVING HOUR>=9 and HOUR<20
ORDER BY 1

-- 중성화 여부 파악하기
SELECT ANIMAL_ID, NAME, 
    CASE
        WHEN SEX_UPON_INTAKE LIKE 'Intact%' THEN 'X'
        ELSE 'O'
    END '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

-- DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME
    ,DATE_FORMAT(DATETIME,'%Y-%m-%d') AS '날짜'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID


