-- 상품을 구매한 회원 비율 구하기
WITH all_users AS (SELECT COUNT(USER_ID) AS TOTAL FROM USER_INFO WHERE YEAR(JOINED)=2021)

SELECT YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(distinct USER_ID) AS PUCHASED_USERS, 
    ROUND(COUNT(distinct USER_ID)/TOTAL, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE as s, all_users
WHERE USER_ID IN (SELECT USER_ID AS TOTAL FROM USER_INFO WHERE YEAR(JOINED)=2021)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
