-- 가격이 제일 비싼 식품의 정보 출력하기
SELECT PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CD,
    CATEGORY,
    PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)


-- 카테고리 별 상품 개수 구하기
SELECT LEFT(PRODUCT_CODE,2) AS 'CATEGORY',
    COUNT(PRODUCT_ID) AS 'PRODUCTS'
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY


-- 진료과별 총 예약 횟수 출력하기
SELECT MCDP_CD AS '진료과 코드',
    COUNT(MCDP_CD) AS '5월예약건수'
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD,'%Y-%m')='2022-05'
GROUP BY MCDP_CD
ORDER BY 2,1


-- 상품 별 오프라인 매출 구하기
SELECT p.PRODUCT_CODE,
    SUM(p.PRICE*o.SALES_AMOUNT) AS 'SALES'
FROM PRODUCT p
LEFT JOIN OFFLINE_SALE o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE


-- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기
SELECT CAR_TYPE,
    COUNT(CAR_ID) AS 'CARS'
FROM CAR_RENTAL_COMPANY_CAR 
WHERE OPTIONS LIKE '%시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE


-- 3월에 태어난 여성 회원 목록 출력하기
SELECT MEMBER_ID,
    MEMBER_NAME,
    GENDER,
    DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS 'DATE_OF_BIRTH'
FROM MEMBER_PROFILE 
WHERE DATE_FORMAT(DATE_OF_BIRTH,'%m')='03'
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID


-- 조건에 맞는 도서와 저자 리스트 출력하기
SELECT BOOK_ID,
    AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS 'PUBLISHED_DATE'
FROM BOOK AS b
LEFT JOIN AUTHOR AS a
ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE


-- 성분으로 구분한 아이스크림 총 주문량
SELECT INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) AS 'TOTAL_ORDER'
FROM FIRST_HALF AS f
LEFT JOIN ICECREAM_INFO AS i
ON f.FLAVOR = i.FLAVOR
GROUP BY i.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER


-- 가격대 별 상품 개수 구하기
SELECT 
    (PRICE div 10000)*10000 AS 'PRICE_GROUP',
    COUNT(PRODUCT_ID) AS 'PRODUCTS'
FROM PRODUCT 
GROUP BY 1
ORDER BY 1


-- 재구매가 일어난 상품과 회원 리스트 구하기
SELECT USER_ID,
    PRODUCT_ID
FROM ONLINE_SALE 
GROUP BY PRODUCT_ID, USER_ID
HAVING COUNT(USER_ID)>1
ORDER BY USER_ID, PRODUCT_ID DESC


-- 조건에 부합하는 중고거래 상태 조회하기
SELECT BOARD_ID,
    WRITER_ID,
    TITLE,
    PRICE,
    CASE WHEN STATUS='SALE' THEN '판매중'
        WHEN STATUS='RESERVED' THEN '예약중'
        WHEN STATUS='DONE' THEN '거래완료' 
    END AS 'STATUS'
FROM USED_GOODS_BOARD 
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC


-- 자동차 평균 대여 기간 구하기
-- * 대여 시작일 포함위해 +1 해야 함
SELECT CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE,START_DATE)+1),1) AS 'AVERAGE_DURATION'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
