-- 중복 제거하기
SELECT COUNT(distinct(NAME))
FROM ANIMAL_INS

-- 아픈 동물 찾기 
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'

-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE
    ,COUNT(ANIMAL_ID) AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

-- 여러 기준으로 정렬하기
-- (이름 순으로 조회. 단, 이름이 같은 동물은 보호를 나중에 시작한 동물을 먼저 보여준다)
SELECT ANIMAL_ID
	,NAME
	,DATETIME
FROM ANIMAL_INS
ORDER BY 2, 3 DESC

-- 상위 n개 레코드
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

-- 이름이 없는 동물의 아이디
-- (※ NAME=NULL 과 IS NULL 차이)
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID
